// TB-2/TB-6 scripted-check harness (m3-04, docs/planning/05-c-toolbelt.md
// section 4.3's verification text: "add fixture, supabase db push, ...
// asserts the entry"). Stands up:
//
//   1. A REAL, disposable local PostgreSQL 16 database (this sandbox's
//      already-running cluster -- `sudo -n -u postgres psql`), with the
//      real `core.app` DDL (apps/toolbelt/supabase/migrations/
//      20260806190000_core_create_schema.sql's core.app table plus
//      20260812230000_core_app_registry_extension.sql's registry columns)
//      and the three REAL registration migrations already committed to this
//      repo (prompt-organizer, network-checker, idea-intake) applied
//      byte-for-byte, unmodified, via `psql -f -` with the checkout-owning
//      process streaming each file to the `postgres` user over stdin.
//   2. A fixture tool, generated by the REAL packages/toolbelt-cli `tool:new`
//      binary (not reimplemented) against a scratch `--toolbelt-root`
//      OUTSIDE this git working tree entirely (os.tmpdir(), never under
//      apps/toolbelt/ or apps/shell/) -- so the whole "add a tool" step
//      touches zero files this repo tracks, which is a strictly stronger
//      proof of TB-2's "zero Shell code change" than putting the fixture
//      under apps/toolbelt/** would have been (see this issue's own report
//      for the reasoning). The fixture's generated schema-creation and
//      registration migrations are then applied the same way as step 1's
//      real migrations.
//   3. A tiny local HTTP server that answers PostgREST's own querystring
//      convention for `GET /rest/v1/app` (`select=`, `status=in.(...)`,
//      `kind=in.(...)`, `id=eq.<id>`, `limit=`) by running a REAL SQL query
//      against the REAL database from step 1/2 and returning the REAL rows
//      as JSON -- see this issue's report for why this stands in for a real
//      PostgREST binary and exactly what it does and does not prove.
//
// Bootstrap scaffolding (create_schema.sql's core.run has
// `user_id uuid references auth.users(id) default auth.uid()`, and its own
// `grant ... to anon, authenticated, service_role` needs those three roles
// to exist): NOT part of any real migration, added here purely so the real
// migration files can be applied unmodified against a vanilla (non-Supabase)
// Postgres 16 instance. `anon`/`authenticated`/`service_role` are created
// with an idempotent existence check because they are CLUSTER-WIDE
// (CREATE ROLE, unlike CREATE SCHEMA, is not scoped to one database) and
// other sessions in this same sandbox have already created them for their
// own scratch databases (confirmed via `\du` before writing this file).
import { execFileSync } from "node:child_process";
import { createServer } from "node:http";
import { copyFileSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(HERE, "../../../../.."); // e2e/support -> e2e -> frontend -> shell -> apps -> repo root
const TOOLBELT_MIGRATIONS_DIR = path.join(REPO_ROOT, "apps/toolbelt/supabase/migrations");
const TOOLBELT_ROOT_MANIFEST = path.join(REPO_ROOT, "apps/toolbelt/tool.json");
const TOOLBELT_CLI_BIN = path.join(REPO_ROOT, "packages/toolbelt-cli/bin/tool.mjs");

// The exact real migration files this harness applies, in order, to build a
// faithful `core.app` table: the table shape (create_schema), the m3-02
// registry-extension columns, then the three real tools already registered
// in this repo today -- giving the fixture row real siblings (a route-
// bearing UI tool with a Shell page of its own already, a routeless CLI
// tool, and a second route-bearing UI tool) to prove the split against,
// not just an empty table plus one fixture.
const REAL_MIGRATIONS = [
  "20260806190000_core_create_schema.sql",
  "20260812230000_core_app_registry_extension.sql",
  "20260812240000_register_prompt-organizer.sql",
  "20260812250000_register_network-checker.sql",
  "20260813003000_register_idea-intake.sql",
];

const BOOTSTRAP_ROLES_SQL = `
do $$
begin
  if not exists (select from pg_roles where rolname = 'anon') then
    create role anon;
  end if;
  if not exists (select from pg_roles where rolname = 'authenticated') then
    create role authenticated;
  end if;
  if not exists (select from pg_roles where rolname = 'service_role') then
    create role service_role;
  end if;
end
$$;
`;

// Minimal Supabase-shaped scaffolding, PER DATABASE (schemas/tables are
// database-scoped, unlike the roles above) -- just enough for
// core_create_schema.sql's auth.users FK and auth.uid() default to resolve
// on a vanilla Postgres 16 instance with no real Supabase Auth installed.
const BOOTSTRAP_AUTH_SQL = `
create schema auth;
create table auth.users (id uuid primary key);
create function auth.uid() returns uuid language sql stable as $$ select null::uuid $$;
`;

function sudoPostgres(args: string[], input?: string): string {
  return execFileSync("sudo", ["-n", "-u", "postgres", ...args], { encoding: "utf8", input });
}

function psqlFile(dbName: string, filePath: string): void {
  // GitHub's runner checkout is not necessarily traversable by the
  // `postgres` OS user. Read as the checkout owner, then preserve psql's
  // file-processing mode while sending the exact script over stdin.
  sudoPostgres(
    ["psql", "-v", "ON_ERROR_STOP=1", "-d", dbName, "-f", "-"],
    readFileSync(filePath, "utf8")
  );
}

function psqlInline(dbName: string, sql: string): void {
  sudoPostgres(["psql", "-v", "ON_ERROR_STOP=1", "-d", dbName, "-c", sql]);
}

function psqlJsonQuery(dbName: string, sql: string): string {
  return sudoPostgres(["psql", "-d", dbName, "-t", "-A", "-v", "ON_ERROR_STOP=1", "-c", sql]).trim();
}

function uniqueDbName(): string {
  const pid = process.pid;
  const ts = Date.now();
  const rand = Math.floor(Math.random() * 1_000_000);
  return `m3_04_shell_registry_e2e_${pid}_${ts}_${rand}`;
}

export interface RegisteredRow {
  id: string;
  name: string;
  schema_name: string;
  status: string;
  kind: string;
  route: string | null;
  version: string;
  description: string | null;
  manifest_hash: string | null;
  registered_at: string | null;
}

export interface RegistryFixture {
  dbName: string;
  /** Base URL of the local Postgres-backed PostgREST-shaped shim, e.g. http://127.0.0.1:54871 */
  shimBaseUrl: string;
  fixtureId: string;
  fixtureName: string;
  fixtureRoute: string;
  /** Directly reads the fixture row back with a real SQL SELECT (bypassing the shim/HTTP layer) -- used to assert against ground truth. */
  readFixtureRow(): RegisteredRow | null;
  /** `update core.app set status = <status> where id = <fixtureId>` -- the "SQL sets the fixture row retired" step, and its reverse. */
  setFixtureStatus(status: "idea" | "building" | "live" | "retired"): void;
  /** Applies the REAL, toolbelt-cli-generated `register_<id>_down.sql` for the fixture, byte for byte. */
  applyFixtureDownMigration(): void;
  /** Drops the scratch database and removes the scratch toolbelt-root directory (outside the repo) and stops the shim server. */
  teardown(): void;
}

export async function setupRegistryFixture(): Promise<RegistryFixture> {
  const dbName = uniqueDbName();
  sudoPostgres(["createdb", dbName]);

  psqlInline(dbName, BOOTSTRAP_ROLES_SQL);
  psqlInline(dbName, BOOTSTRAP_AUTH_SQL);

  for (const filename of REAL_MIGRATIONS) {
    psqlFile(dbName, path.join(TOOLBELT_MIGRATIONS_DIR, filename));
  }

  // Step 2: generate the fixture via the REAL scaffold CLI, entirely
  // outside the git working tree (see this file's header comment). Seed the
  // disposable root with the real Toolbelt spine manifest and migration
  // directory: `tool:new --toolbelt-root` intentionally requires both so
  // timestamp allocation and ownership checks see a valid Toolbelt root.
  const scratchToolbeltRoot = mkdtempSync(path.join(tmpdir(), "m3-04-toolbelt-fixture-"));
  mkdirSync(path.join(scratchToolbeltRoot, "supabase", "migrations"), { recursive: true });
  copyFileSync(TOOLBELT_ROOT_MANIFEST, path.join(scratchToolbeltRoot, "tool.json"));

  const fixtureId = "e2e-fixture-tool";
  const fixtureName = "E2E Fixture Tool";
  const fixtureRoute = "/e2e-fixture-tool";

  execFileSync(
    process.execPath,
    [
      TOOLBELT_CLI_BIN,
      "--id",
      fixtureId,
      "--name",
      fixtureName,
      "--kind",
      "ui",
      "--route",
      fixtureRoute,
      "--toolbelt-root",
      scratchToolbeltRoot,
    ],
    { encoding: "utf8" }
  );

  const fixtureMigrationsDir = path.join(scratchToolbeltRoot, "supabase", "migrations");
  const fixtureToolMigrationsDir = path.join(scratchToolbeltRoot, "apps", fixtureId, "supabase", "migrations");

  const schemaUpFile = readdirSync(fixtureToolMigrationsDir)
    .find((f) => f.endsWith("_create_schema.sql"));
  if (!schemaUpFile) throw new Error("registry-fixture: scaffold CLI did not generate a schema migration");
  psqlFile(dbName, path.join(fixtureToolMigrationsDir, schemaUpFile));

  const registerUpFile = readdirSync(fixtureMigrationsDir)
    .find((f) => f.includes(`_register_${fixtureId}.sql`));
  const registerDownFile = readdirSync(fixtureMigrationsDir)
    .find((f) => f.includes(`_register_${fixtureId}_down.sql`));
  if (!registerUpFile || !registerDownFile) {
    throw new Error("registry-fixture: scaffold CLI did not generate a registration migration pair");
  }
  const registerUpPath = path.join(fixtureMigrationsDir, registerUpFile);
  const registerDownPath = path.join(fixtureMigrationsDir, registerDownFile);
  psqlFile(dbName, registerUpPath);

  // Step 3: the local Postgres-backed shim.
  const server = createServer((req, res) => {
    try {
      const url = new URL(req.url ?? "/", "http://127.0.0.1");
      if (req.method !== "GET" || url.pathname !== "/rest/v1/app") {
        res.writeHead(404, { "content-type": "application/json" }).end(JSON.stringify({ message: "not found" }));
        return;
      }
      const where: string[] = [];
      const status = url.searchParams.get("status");
      if (status !== null) where.push(pgInFilter("status", status));
      const kind = url.searchParams.get("kind");
      if (kind !== null) where.push(pgInFilter("kind", kind));
      const id = url.searchParams.get("id");
      if (id !== null) where.push(pgEqFilter("id", id));
      const limit = url.searchParams.get("limit");
      const limitN = limit !== null ? Number.parseInt(limit, 10) : null;

      const whereSql = where.length > 0 ? `where ${where.join(" and ")}` : "";
      const limitSql = limitN !== null && Number.isFinite(limitN) ? `limit ${limitN}` : "";
      const sql = `select coalesce(json_agg(row_to_json(t)), '[]'::json)::text from (
        select id, name, schema_name, status, kind, route, version, description, manifest_hash, registered_at
        from core.app
        ${whereSql}
        order by id asc
        ${limitSql}
      ) t;`;

      const body = psqlJsonQuery(dbName, sql);
      res.writeHead(200, { "content-type": "application/json" });
      res.end(body);
    } catch (error) {
      res.writeHead(500, { "content-type": "application/json" });
      res.end(JSON.stringify({ message: error instanceof Error ? error.message : String(error) }));
    }
  });

  const port = await new Promise<number>((resolve, reject) => {
    server.once("error", reject);
    server.listen(0, "127.0.0.1", () => {
      const address = server.address();
      if (address === null || typeof address === "string") {
        reject(new Error("registry-fixture: shim server did not report a port"));
        return;
      }
      resolve(address.port);
    });
  });

  function readFixtureRow(): RegisteredRow | null {
    const sql = `select coalesce(json_agg(row_to_json(t)), '[]'::json)::text from (
      select id, name, schema_name, status, kind, route, version, description, manifest_hash, registered_at
      from core.app where id = ${pgQuote(fixtureId)}
    ) t;`;
    const rows = JSON.parse(psqlJsonQuery(dbName, sql)) as RegisteredRow[];
    return rows[0] ?? null;
  }

  function setFixtureStatus(next: "idea" | "building" | "live" | "retired"): void {
    psqlInline(dbName, `update core.app set status = ${pgQuote(next)} where id = ${pgQuote(fixtureId)};`);
  }

  function applyFixtureDownMigration(): void {
    psqlFile(dbName, registerDownPath);
  }

  function teardown(): void {
    server.close();
    try {
      sudoPostgres(["dropdb", dbName]);
    } finally {
      rmSync(scratchToolbeltRoot, { recursive: true, force: true });
    }
  }

  return {
    dbName,
    shimBaseUrl: `http://127.0.0.1:${port}`,
    fixtureId,
    fixtureName,
    fixtureRoute,
    readFixtureRow,
    setFixtureStatus,
    applyFixtureDownMigration,
    teardown,
  };
}

function pgQuote(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function pgInFilter(column: "status" | "kind", raw: string): string {
  const m = /^in\.\((.*)\)$/.exec(raw);
  if (!m) throw new Error(`registry-fixture shim: unsupported filter for ${column}: ${raw}`);
  const values = m[1]
    .split(",")
    .map((v) => v.trim())
    .filter(Boolean)
    .map(pgQuote);
  if (values.length === 0) return `false`; // PostgREST semantics: in.() matches nothing
  return `${column} in (${values.join(",")})`;
}

function pgEqFilter(column: "id", raw: string): string {
  const m = /^eq\.(.*)$/.exec(raw);
  if (!m) throw new Error(`registry-fixture shim: unsupported filter for ${column}: ${raw}`);
  return `${column} = ${pgQuote(m[1])}`;
}

// Re-exported for the spec's own logging/diagnostics.
export { REAL_MIGRATIONS, TOOLBELT_MIGRATIONS_DIR };
