"""Mint a read-only agent JWT for the lifeos MCP server (ADR 010).

Usage: `python scripts/mint_agent_token.py --scope relationships:read
--scope health:read [--agent claude-desktop] [--days 30] [--install]`.
Reads LIFEOS_AGENT_JWT_PRIVATE_KEY (base64-wrapped PEM; generated by the
guards keygen script — see README "Agent access over MCP") from the
environment or the repo .env. Prints the token, or with `--install` writes
it into the repo .env as LIFEOS_AGENT_TOKEN where the server's env fallback
finds it — the path the guards `lifeos-mcp-setup.ps1` one-click uses, so no
token material ever needs copying. Refuses any scope that is not
`<domain>:read`; re-run with the new domain's scope when one lands.
"""

import argparse
import sys
from pathlib import Path

from kernel.env import read_env
from mcp_server.tokens import AgentTokenError, decode_key, mint

ENV_FILE = Path(__file__).resolve().parents[1] / ".env"


def upsert_env(path: Path, name: str, value: str) -> None:
    """Replace or append a NAME=value line, preserving everything else."""
    lines = path.read_text(encoding="utf-8-sig").splitlines() if path.exists() else []
    replaced = False
    for i, line in enumerate(lines):
        if line.strip().startswith(f"{name}="):
            lines[i] = f"{name}={value}"
            replaced = True
    if not replaced:
        lines.append(f"{name}={value}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--scope",
        action="append",
        required=True,
        dest="scopes",
        help="a '<domain>:read' scope; repeat per domain",
    )
    parser.add_argument("--agent", default="claude-desktop", help="token subject suffix")
    parser.add_argument("--days", type=int, default=30, help="days until expiry")
    parser.add_argument(
        "--install",
        action="store_true",
        help="write the token to the repo .env as LIFEOS_AGENT_TOKEN instead of printing it",
    )
    args = parser.parse_args()
    key = read_env("LIFEOS_AGENT_JWT_PRIVATE_KEY")
    if not key:
        print(
            "LIFEOS_AGENT_JWT_PRIVATE_KEY is not set; run the keygen script first "
            "(README: Agent access over MCP)",
            file=sys.stderr,
        )
        return 2
    try:
        token = mint(decode_key(key), args.scopes, agent=args.agent, days=args.days)
    except AgentTokenError as exc:
        print(str(exc), file=sys.stderr)
        return 2
    if args.install:
        upsert_env(ENV_FILE, "LIFEOS_AGENT_TOKEN", token)
        print(
            f"wrote LIFEOS_AGENT_TOKEN to .env "
            f"(agent={args.agent}, scopes={' '.join(sorted(args.scopes))}, {args.days} days)"
        )
    else:
        print(token)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
