/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/healthz": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Healthz
     * @description Liveness for deploys and the compose healthcheck. Touches no data.
     */
    get: operations["get_healthz_healthz_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/types": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Types */
    get: operations["get_types_types_get"];
    put?: never;
    /** Post Types */
    post: operations["post_types_types_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/capture": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Post Capture */
    post: operations["post_capture_capture_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/edges": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Post Edges */
    post: operations["post_edges_edges_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/entities/{entity_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Entity Route */
    get: operations["get_entity_route_entities__entity_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/entities/{entity_id}/forget": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Post Forget
     * @description Erasure by redaction (ADR 007). Send `{}` to erase every flagged field.
     */
    post: operations["post_forget_entities__entity_id__forget_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/entities/{entity_id}/history": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get History */
    get: operations["get_history_entities__entity_id__history_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/search": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Search */
    get: operations["get_search_search_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** CaptureIn */
    CaptureIn: {
      /** Type Name */
      type_name: string;
      /** Attributes */
      attributes: {
        [key: string]: unknown;
      };
      /** Valid Time */
      valid_time?: string | null;
      /**
       * Actor
       * @default kyle
       */
      actor: string;
    };
    /** CaptureResult */
    CaptureResult: {
      /**
       * Entity Id
       * Format: uuid
       */
      entity_id: string;
      resolution: components["schemas"]["Resolution"];
    };
    /** DefineTypeIn */
    DefineTypeIn: {
      /** Name */
      name: string;
      /** Domain */
      domain: string;
      /** Json Schema */
      json_schema: {
        [key: string]: unknown;
      };
      /** Parent */
      parent?: string | null;
    };
    /** Edge */
    Edge: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * From Entity
       * Format: uuid
       */
      from_entity: string;
      /** Relation */
      relation: string;
      /**
       * To Entity
       * Format: uuid
       */
      to_entity: string;
      /** Attributes */
      attributes: {
        [key: string]: unknown;
      };
      /**
       * Valid From
       * Format: date-time
       */
      valid_from: string;
      /** Valid To */
      valid_to?: string | null;
      /**
       * Recorded At
       * Format: date-time
       */
      recorded_at: string;
      /** Superseded At */
      superseded_at?: string | null;
    };
    /** Entity */
    Entity: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name?: string | null;
      /** Attributes */
      attributes: {
        [key: string]: unknown;
      };
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** EntityView */
    EntityView: {
      entity: components["schemas"]["Entity"];
      /** Types */
      types: string[];
      /** Edges Out */
      edges_out: components["schemas"]["Edge"][];
      /** Edges In */
      edges_in: components["schemas"]["Edge"][];
    };
    /** Event */
    Event: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Entity Id */
      entity_id?: string | null;
      /** Event Type */
      event_type: string;
      /** Payload */
      payload: {
        [key: string]: unknown;
      };
      /**
       * Valid Time
       * Format: date-time
       */
      valid_time: string;
      /**
       * Recorded At
       * Format: date-time
       */
      recorded_at: string;
      /** Actor */
      actor: string;
    };
    /**
     * ForgetIn
     * @description `fields=None` erases every x-pii field the entity's types declare.
     */
    ForgetIn: {
      /** Fields */
      fields?: string[] | null;
      /**
       * Actor
       * @default kyle
       */
      actor: string;
    };
    /** ForgetResult */
    ForgetResult: {
      /**
       * Entity Id
       * Format: uuid
       */
      entity_id: string;
      /** Fields */
      fields: string[];
      /** Events Redacted */
      events_redacted: number;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** RelateIn */
    RelateIn: {
      /**
       * From Id
       * Format: uuid
       */
      from_id: string;
      /** Relation */
      relation: string;
      /**
       * To Id
       * Format: uuid
       */
      to_id: string;
      /**
       * Valid From
       * Format: date-time
       */
      valid_from: string;
      /** Attributes */
      attributes?: {
        [key: string]: unknown;
      } | null;
    };
    /**
     * Resolution
     * @enum {string}
     */
    Resolution: "new" | "match" | "ambiguous";
    /** TypeDefinition */
    TypeDefinition: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Domain */
      domain: string;
      /** Json Schema */
      json_schema: {
        [key: string]: unknown;
      };
      /** Parent Type Id */
      parent_type_id?: string | null;
      /**
       * Is Active
       * @default true
       */
      is_active: boolean;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  get_healthz_healthz_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
  get_types_types_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TypeDefinition"][];
        };
      };
    };
  };
  post_types_types_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DefineTypeIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TypeDefinition"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  post_capture_capture_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CaptureIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CaptureResult"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  post_edges_edges_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RelateIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Edge"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_entity_route_entities__entity_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        entity_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EntityView"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  post_forget_entities__entity_id__forget_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        entity_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ForgetIn"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ForgetResult"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_history_entities__entity_id__history_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        entity_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Event"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_search_search_get: {
    parameters: {
      query?: {
        type_name?: string | null;
        text?: string | null;
        filters?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Entity"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
