-- Independent security review, Finding 43 (re-verified against current
-- HEAD): apps/toolbelt/tool.json's own `register` field still read the
-- scaffold placeholder "pending-m3-02" verbatim, and no migration had ever
-- inserted a core.app row for id 'toolbelt' -- the root spine itself (the
-- monorepo's own owner of the core/idea schemas, the shared registry table
-- it registers everyone else into) was the one manifest in this repo that
-- was never actually registered in that same registry. Every other real
-- tool (prompt-organizer, network-checker, idea-intake) already has its own
-- registration migration; this is the toolbelt root's.
--
-- Generated by hand (packages/toolbelt-cli's generator does not scaffold a
-- registration migration for the pre-existing root spine manifest, only for
-- new tools created via tool:new), mirroring
-- apps/toolbelt/supabase/migrations/20260813003000_register_idea-intake.sql's
-- shape exactly: one idempotent upsert of the core.app row from tool.json's
-- fields, `status` deliberately absent from the ON CONFLICT SET list (same
-- reasoning as every other registration migration in this repo -- re-running
-- registration must never clobber a status a separate, dedicated
-- status-transition migration set).
--
-- schema_name: core.app.schema_name is a single NOT NULL text column, but
-- the root spine's own tool.json declares TWO owned schemas
-- (`"schemas": ["core", "idea"]` -- the one documented exception in
-- tool.schema.json's own "schemas" property description, per
-- scripts/validate-manifests.mjs's ROOT_SPINE_EXCEPTION_SCHEMAS). 'core' is
-- recorded here as the nominal primary identifier: it is the schema this
-- manifest's own `permissions.db.read`/`write` arrays list first, the
-- schema every other tool's own core.app row (and core.log_run) writes
-- through, and the schema this manifest's `entry.headless.command`
-- (`select core.purge_old_events();`) directly names -- `idea` is real but
-- secondary. Same posture as
-- 20260812250000_register_network-checker.sql's own schema_name judgment
-- call for a manifest whose real ownership does not collapse cleanly onto
-- one column.
--
-- manifest_hash is the sha256 hex digest of the canonicalized manifest
-- (RFC-8785-style key-sorted JSON, no insignificant whitespace), computed by
-- apps/toolbelt/scripts/validate-manifests.mjs's canonicalJSON/manifestHash
-- functions -- imported and called directly against the real, current
-- tool.json on disk (AFTER updating its `register` field to name this exact
-- migration file, since that field is itself part of the hashed manifest),
-- never reimplemented or hand-computed.
-- apps/toolbelt/tests/registration-toolbelt.test.mjs asserts this literal
-- string equals manifestHash() computed fresh over the real manifest file on
-- disk, so the two can never silently drift apart (TB-1b parity,
-- docs/planning/05-c-toolbelt.md section 11).
insert into core.app (
  id, name, schema_name, status, kind, route, version, description,
  manifest, manifest_hash, registered_at
)
values (
  'toolbelt',
  'Toolbelt Root Spine',
  'core',
  'building',
  'headless',
  null,
  '0.1.0',
  'Shared root spine of the Toolbelt monorepo: owns the core schema (runs, costs, outcomes, metrics, events) that every tool writes through via core.log_run, plus the idea schema for the curated portfolio backlog. Not itself a UI or CLI surface.',
  '{"description":"Shared root spine of the Toolbelt monorepo: owns the core schema (runs, costs, outcomes, metrics, events) that every tool writes through via core.log_run, plus the idea schema for the curated portfolio backlog. Not itself a UI or CLI surface.","entry":{"headless":{"command":"select core.purge_old_events();","schedule":"0 3 * * *"}},"id":"toolbelt","kind":"headless","lifecycle":{"health":"node --test \"tests/*.test.mjs\"","migrate":"gh workflow run platform-migrations.yml","register":"20260814110000_register_toolbelt.sql"},"name":"Toolbelt Root Spine","ownership":{"owner":"kylegsmith19@gmail.com","path":"apps/toolbelt"},"permissions":{"db":{"read":["core","idea"],"write":["core","idea"]},"llmHandler":{"access":false},"networkEgress":[]},"schemas":["core","idea"],"version":"0.1.0"}'::jsonb,
  '9047af64aa7e5db516e2291f9b0bb4777cf4d9f56c2ad7b3f80749fa9f190828',
  now()
)
on conflict (id) do update set
  name          = excluded.name,
  schema_name   = excluded.schema_name,
  kind          = excluded.kind,
  route         = excluded.route,
  version       = excluded.version,
  description   = excluded.description,
  manifest      = excluded.manifest,
  manifest_hash = excluded.manifest_hash,
  registered_at = excluded.registered_at;
