// Generated by packages/toolbelt-cli's tool:new (docs/planning/05-c-toolbelt.md
// section 5.1 generated layout: "tests/registration.test.mjs (asserts
// manifest validity and registry row parity)"). Mirrors
// apps/toolbelt/tests/registry-manifest-hash.test.mjs's proof, scoped to just
// this one tool: (1) this tool's own tool.json is schema-valid, and (2) the
// registration migration's literal manifest_hash equals manifestHash()
// recomputed fresh from that same tool.json, so the two can never silently
// drift apart (TB-1b parity).
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { checkManifestShape, manifestHash } from "../../../scripts/validate-manifests.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const TOOL_DIR = join(__dirname, "..");
const MANIFEST_PATH = join(TOOL_DIR, "tool.json");
const MIGRATION_PATH = join(TOOL_DIR, "..", "..", "supabase", "migrations", "20260813002605_register_idea-intake.sql");

// The hash sits on its own line as a bare single-quoted 64-hex-char literal,
// same anchoring rationale as registry-manifest-hash.test.mjs: the whole
// trimmed line must be exactly this, so it cannot match a substring inside
// the much longer minified-JSON manifest literal on the preceding line.
const HASH_LINE_RE = /^\s*'([0-9a-f]{64})',\s*$/m;

test("tool.json conforms to tool.schema.json", () => {
  const failures = checkManifestShape([MANIFEST_PATH]);
  assert.deepEqual(failures, []);
});

test("the registration migration's literal manifest_hash equals manifestHash() over the real tool.json on disk", () => {
  const sql = readFileSync(MIGRATION_PATH, "utf8");
  const match = HASH_LINE_RE.exec(sql);
  assert.ok(match, "expected exactly one bare 64-hex-char single-quoted literal line in the migration");

  const manifest = JSON.parse(readFileSync(MANIFEST_PATH, "utf8"));
  assert.equal(
    match[1],
    manifestHash(manifest),
    "manifest_hash in the registration migration no longer matches tool.json -- regenerate the registration migration",
  );
});
