"""Mint a read-only agent JWT for the lifeos MCP server (ADR 010).

Usage: `python scripts/mint_agent_token.py --scope relationships:read
--scope health:read [--agent claude-desktop] [--days 30]`. Reads
LIFEOS_AGENT_JWT_PRIVATE_KEY (base64-wrapped PEM; generated by the guards
keygen script — see README "Agent access over MCP") from the environment or
the repo .env and prints the token. Refuses any scope that is not
`<domain>:read`; re-run with the new domain's scope when one lands.
"""

import argparse
import sys

from kernel.env import read_env
from mcp_server.tokens import AgentTokenError, decode_key, mint


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--scope",
        action="append",
        required=True,
        dest="scopes",
        help="a '<domain>:read' scope; repeat per domain",
    )
    parser.add_argument("--agent", default="claude-desktop", help="token subject suffix")
    parser.add_argument("--days", type=int, default=30, help="days until expiry")
    args = parser.parse_args()
    key = read_env("LIFEOS_AGENT_JWT_PRIVATE_KEY")
    if not key:
        print(
            "LIFEOS_AGENT_JWT_PRIVATE_KEY is not set; run the keygen script first "
            "(README: Agent access over MCP)",
            file=sys.stderr,
        )
        return 2
    try:
        print(mint(decode_key(key), args.scopes, agent=args.agent, days=args.days))
    except AgentTokenError as exc:
        print(str(exc), file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
