-- Down migration for 20260806190200_rls_baseline.sql.
drop policy if exists owner_all on core.run;
drop policy if exists authenticated_all on core.app;
drop policy if exists authenticated_all on core.event;
drop policy if exists authenticated_all on core.cost;
drop policy if exists authenticated_all on core.outcome;
drop policy if exists authenticated_all on core.run_outcome;
drop policy if exists authenticated_all on core.metric_def;
drop policy if exists authenticated_all on core.metric_value;
drop policy if exists authenticated_all on core.assumption;
drop policy if exists authenticated_all on core.intervention;
drop policy if exists authenticated_all on idea.idea;
drop policy if exists authenticated_all on idea.dependency;
drop policy if exists authenticated_all on idea.score;

alter table core.run no force row level security;
alter table core.run disable row level security;
alter table core.app no force row level security;
alter table core.app disable row level security;
alter table core.event no force row level security;
alter table core.event disable row level security;
alter table core.cost no force row level security;
alter table core.cost disable row level security;
alter table core.outcome no force row level security;
alter table core.outcome disable row level security;
alter table core.run_outcome no force row level security;
alter table core.run_outcome disable row level security;
alter table core.metric_def no force row level security;
alter table core.metric_def disable row level security;
alter table core.metric_value no force row level security;
alter table core.metric_value disable row level security;
alter table core.assumption no force row level security;
alter table core.assumption disable row level security;
alter table core.intervention no force row level security;
alter table core.intervention disable row level security;
alter table idea.idea no force row level security;
alter table idea.idea disable row level security;
alter table idea.dependency no force row level security;
alter table idea.dependency disable row level security;
alter table idea.score no force row level security;
alter table idea.score disable row level security;
